version: "3.7"
services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - 27017:27017
    volumes:
      - ./src:/var/lib/mongo
    
  mongo-express:
    image: mongo-express
    container_name: mongodb-express
    restart: always
    port:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      

    